sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run docker-react npm run test -- --coverage
deploy:
  provider: elasticebeanstalk
  region: "us-west-2"
  app: gsg-signup
  env: GsgSignup-env
  bucket_name: elasticbeanstalk-us-west-2-354844110981
  bucket_path: gsg-signup
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
